//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkribisFAM.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AkribisFAM.Lang.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 系统日志 的本地化字符串。
        /// </summary>
        public static string debugLog {
            get {
                return ResourceManager.GetString("debugLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络配置 的本地化字符串。
        /// </summary>
        public static string internetConfig {
            get {
                return ResourceManager.GetString("internetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主界面 的本地化字符串。
        /// </summary>
        public static string mainPageLabel {
            get {
                return ResourceManager.GetString("mainPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动控制 的本地化字符串。
        /// </summary>
        public static string manualConfig {
            get {
                return ResourceManager.GetString("manualConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数配置 的本地化字符串。
        /// </summary>
        public static string parameterConfigure {
            get {
                return ResourceManager.GetString("parameterConfigure", resourceCulture);
            }
        }
    }
}
